FROM alpine:latest

RUN apk update && apk add nginx && rm -rf /var/cache/apk/*

RUN echo "<h1>Application Deployed via Terraform IaC!</h1>" > /var/www/localhost/htdocs/index.html

RUN printf 'server {\n\
    listen 80 default_server;\n\
    root /var/www/localhost/htdocs;\n\
    index index.html;\n\
    location / { try_files $uri $uri/ =404; }\n\
}\n' > /etc/nginx/http.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]