name: Terraform IaC CI/CD

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest

    steps:
      # --- Préparation (Setup) ---
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # --- Initialisation ---
      - name: Terraform Init
        run: terraform init

      # --- Validation & Revue ---
      - name: Terraform Plan
        id: plan
        run: terraform plan -var="db_password=${{ secrets.DB_PASSWORD }}"

      # --- Déploiement Continu ---
      # N'est exécuté que si l'étape Plan précédente a réussi
      - name: Terraform Apply
        if: steps.plan.outcome == 'success'
        run: terraform apply -auto-approve -var="db_password=${{ secrets.DB_PASSWORD }}"